import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const ResearchSection = () => {
  const currentPapers = [
    {
      title: "The Crowdless Future? Generative AI and Creative Problem Solving",
      authors: "Léonard Boussioux, Jacqueline N. Lane, Miaomiao Zhang, Vladimir Jacimovic, and Karim R. Lakhani",
      venue: (
        <span>
          Published in{" "}
          <a
            href="https://pubsonline.informs.org/doi/10.1287/orsc.2023.18430"
            target="_blank"
            rel="noopener noreferrer"
            className="text-secondary hover:underline"
          >
            Organization Science
          </a>
        </span>
      ),
      abstract: "The rapid advances in generative artificial intelligence (AI) open up attractive opportunities for creative problem-solving through human-guided AI partnerships. To explore this potential, we initiated a crowdsourcing challenge focused on sustainable, circular economy business ideas generated by the human crowd (HC) and collaborative human-AI efforts using two alternative forms of solution search. The challenge attracted 125 global solvers from various industries, and we used strategic prompt engineering to generate the human-AI solutions. We recruited 300 external human evaluators to judge a randomized selection of 13 out of 234 solutions, totaling 3,900 evaluator-solution pairs. Our results indicate that while human crowd solutions exhibited higher novelty—both on average and for highly novel outcomes—human-AI solutions demonstrated superior strategic viability, financial and environmental value, and overall quality. Notably, human-AI solutions cocreated through differentiated search, where human-guided prompts instructed the large language model to sequentially generate outputs distinct from previous iterations, outperformed solutions generated through independent search. By incorporating \"AI in the loop\" into human-centered creative problem-solving, our study demonstrates a scalable, cost-effective approach to augment the early innovation phases and lays the groundwork for investigating how integrating human-AI solution search processes can drive more impactful innovations.",
      status: "Published",
      slides: "https://www.dropbox.com/scl/fi/4dxx88yurb1y98x13v0sn/MiaomiaoZhang_CrowdlessFuture.pdf?rlkey=e9b7nphfufb5cq5ym29rm8pw9&dl=0",
      slidePreview: `${import.meta.env.BASE_URL}crowdless-future-preview.png`,
    },
    {
      title: "Judging the Problem: A Problem-Centric Approach to Evaluating Early-Stage Ventures",
      authors: "Jacqueline N. Lane, and Miaomiao Zhang",
      venue: (
        <span>
          Available at{" "}
          <a
            href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6072548"
            target="_blank"
            rel="noopener noreferrer"
            className="text-secondary hover:underline"
          >
            SSRN
          </a>
        </span>
      ),
      abstract: "Evaluating early-stage ventures requires experts to assess uncertain opportunities across multiple criteria. This paper examines how emphasizing the customer problem—whether a venture addresses a compelling problem for a clearly defined customer—affects evaluations across professional backgrounds. We conducted a randomized controlled trial at a premier venture competition where 178 judges evaluated 109 ventures (1,153 venture-judge assessments). Our intervention asked judges to prioritize the problem and customer criterion. Treatment effects varied across professional backgrounds: Compared to controls, treated investors rated business model 11% lower, whereas treated entrepreneurs rated impact 12% higher. Domain experts scrutinized problem and customer definition more critically but showed no spillover to other criteria. We demonstrate through a simple intervention how experts use their profession-specific theories of value to assess entrepreneurial ideas.",
      status: "Working Paper",
      // slides: "YOUR_DROPBOX_LINK_HERE?raw=1", // Uncomment and add your Dropbox link
    },
    {
      title: "Who Is a Better Matchmaker? Human vs. Algorithmic Judge Assignment in a High-Stakes Startup Competition",
      authors: "Xi, Sarina, Orelia Pi, Miaomiao Zhang, Jacqueline N. Lane, Nihar B. Shah",
      venue: (
        <span>
          Accepted at IAAI 2026 Innovative Applications of AI. Available at{" "}
          <a
            href="https://arxiv.org/abs/2510.12692"
            target="_blank"
            rel="noopener noreferrer"
            className="text-secondary hover:underline"
          >
            arXiv
          </a>
        </span>
      ),
      abstract: "There is growing interest in applying artificial intelligence (AI) to automate and support complex decision-making tasks. However, it remains unclear how algorithms compare to human judgment in contexts requiring semantic understanding and domain expertise. We examine this in the context of the judge assignment problem, matching submissions to suitably qualified judges. Specifically, we tackled this problem at the Harvard President's Innovation Challenge, the university's premier venture competition awarding over $500,000 to student and alumni startups. This represents a real-world environment where high-quality judge assignment is essential. We developed an AI-based judge-assignment algorithm, Hybrid Lexical-Semantic Similarity Ensemble (HLSE), and deployed it at the competition. We then evaluated its performance against human expert assignments using blinded match-quality scores from judges on 309 judge-venture pairs. Using a Mann-Whitney U statistic based test, we found no statistically significant difference in assignment quality between the two approaches (AUC=0.48,p=0.40); on average, algorithmic matches are rated 3.90 and manual matches 3.94 on a 5-point scale, where 5 indicates an excellent match. Furthermore, manual assignments that previously required a full week could be automated in several hours by the algorithm during deployment. These results demonstrate that HLSE achieves human-expert-level matching quality while offering greater scalability and efficiency, underscoring the potential of AI-driven solutions to support and enhance human decision-making for judge assignment in high-stakes settings.",
      status: "Accepted",
      // slides: "YOUR_DROPBOX_LINK_HERE?raw=1", // Uncomment and add your Dropbox link
    },
    {
      title: "Temporal Distance and Global Knowledge Diffusion on Online Platform",
      authors: "Wesley W. Koo, Miaomiao Zhang, and Prithwiraj (Raj) Choudhury",
      venue: (
        <span>
          Conditional Accept at Strategic Management Journal
        </span>
      ),
      abstract: "Add your abstract here",
      status: "Conditional Accept",
      slides: "https://www.dropbox.com/scl/fi/sajoe9kzuidqbizl85k6l/MiaomiaoZhang_UnwindClock.pdf?rlkey=kl2ktxz0fwcw9m0y9p8mozq61&st=7uxv3yxr&dl=0",
      slidePreview: `${import.meta.env.BASE_URL}temporal-distance-preview.png`,
    },
    {
      title: "Forecasting Impact of Ideas: The Role of Concrete Language in Idea Evaluation",
      authors: "Orwig, William, Jacqueline N. Lane, Miaomiao Zhang, and Daniel L. Schacter",
      description: "Revise & Resubmit",
      status: "Working Paper",
    },
  ];

  const prePhdPapers = [
    {
      title: "Regulatory Uncertainty, Entrepreneurial Entry, and Market Identity Specificity: Evidence from the U.S. Autonomous Vehicle Industry",
      authors: "Jiayi Bao, and Miaomiao Zhang",
      description: "In preparation to submit",
      status: "Work in Progress",
    },
    {
      title: "Organizational-Performance Pay and Compensation Dispersion",
      authors: "Jiayi Bao, Andy Wu, and Miaomiao Zhang",
      venue: (
        <span>
          Published in{" "}
          <a
            href="https://link.springer.com/article/10.1007/s41469-025-00187-3"
            target="_blank"
            rel="noopener noreferrer"
            className="text-secondary hover:underline"
          >
            Journal of Organization Design
          </a>
        </span>
      ),
      abstract: "To drive organizational performance, managers design compensation packages to incentivize the collective contribution of individuals across the organization. Different pay components across individuals may prompt individual concerns based on their views of fairness: those with equity concerns believe that compensation should reflect individual contributions and thus support differences in pay (dispersion), while those with equality concerns believe that similar compensation would be fairer, thus supporting uniform pay (compression). We document the performance implications of compensation dispersion under organizational-performance pay; in increasingly prevalent compensation forms such as stock options or pooled bonuses, individual compensation consists of a pre-designated share of rewards contingent on organizational performance. We argue that prevailing equality concerns under organizational-performance pay generate opposing and asymmetric responses to dispersion from individuals with high vs. low shares of the rewards, leading to lower overall organizational performance under unequal, heterogeneous share dispersion (vs. equal, homogeneous share compression). Evidence from a controlled experiment with online workers and a supplementary field study of professional eSports athletes validates our predictions. Manipulation of two boundary conditions in the experiment further supports the proposed mechanism, as the observed effects are more pronounced when equality concerns are stronger: (1) when the payment scheme involves reward sharing (vs. not) and (2) when the rewards are presented in a percentage framing (vs. a point framing) that facilitates a stronger perception of reward-sharing.",
      status: "Published",
    },
  ];

  return (
    <div className="space-y-6">
      <h2 className="font-display text-2xl font-semibold text-foreground">Research</h2>
      <p className="text-lg text-text-light leading-relaxed">
        My ongoing projects involve working with platforms and innovation institutes to examine customer-problem fit in early-stage entrepreneurial ventures. More specifically, I am investigating how startups can better sample from their potential customer base to improve the scalability and market success of their downstream products and solutions. In the past, I have studied incentive design, AI-augmented problem solving, and knowledge diffusion under open innovation and platform contexts.
      </p>

      <div className="space-y-8">
        {currentPapers.map((paper, index) => (
          paper.slides ? (
            // Papers with slides: displayed as visible cards with two-column layout
            <div key={index} className="border-2 border-secondary rounded-lg p-6 space-y-4 bg-gradient-to-br from-white to-accent/20">
              <div className="space-y-2">
                <h3 className="text-xl font-semibold text-foreground">{paper.title}</h3>
                <p className="text-sm text-text-light">{paper.status}</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Left column: Slides preview */}
                <a
                  href={paper.slides}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block border-2 border-dashed border-secondary rounded-lg overflow-hidden hover:border-solid hover:shadow-xl transition-all group"
                >
                  {paper.slidePreview ? (
                    <img
                      src={paper.slidePreview}
                      alt={`${paper.title} Preview`}
                      className="w-full h-auto object-cover"
                    />
                  ) : (
                    <div className="aspect-video bg-gray-100 flex items-center justify-center">
                      <div className="text-center space-y-2 p-6">
                        <div className="text-5xl">📊</div>
                        <p className="text-lg font-semibold text-foreground">Presentation Slides</p>
                      </div>
                    </div>
                  )}
                  <div className="bg-gray-50 border-t border-border p-3 text-center group-hover:bg-gray-100 transition-colors">
                    <p className="text-sm text-secondary font-medium">
                      Click to view full presentation →
                    </p>
                  </div>
                </a>

                {/* Right column: Paper details */}
                <div className="space-y-3">
                  <p className="text-sm font-medium text-text-light">{paper.authors}</p>
                  {paper.venue && <div className="text-sm text-text-light">{paper.venue}</div>}
                  {paper.abstract && (
                    <div className="space-y-2">
                      <p className="font-semibold text-foreground text-sm">Abstract:</p>
                      <p className="text-text-light leading-relaxed text-sm line-clamp-12">{paper.abstract}</p>
                    </div>
                  )}
                  {paper.description && !paper.abstract && <p className="text-text-light">{paper.description}</p>}
                </div>
              </div>
            </div>
          ) : null
        ))}
      </div>

      {/* Papers without slides: displayed in accordion */}
      <Accordion type="single" collapsible className="w-full mt-6">
        {currentPapers.map((paper, index) => (
          !paper.slides ? (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger className="text-left hover:no-underline">
                <div className="flex flex-col items-start">
                  <span className="font-medium text-foreground">{paper.title}</span>
                  <span className="text-sm text-text-light">{paper.status}</span>
                </div>
              </AccordionTrigger>
              <AccordionContent>
                <div className="space-y-3 pt-2">
                  <p className="text-sm font-medium text-text-light">{paper.authors}</p>
                  {paper.venue && <div className="text-sm text-text-light">{paper.venue}</div>}
                  {paper.abstract && <p className="text-text-light leading-relaxed">{paper.abstract}</p>}
                  {paper.description && !paper.abstract && <p className="text-text-light">{paper.description}</p>}
                </div>
              </AccordionContent>
            </AccordionItem>
          ) : null
        ))}
      </Accordion>

      <div className="mt-8 mb-4">
        <h3 className="font-display text-xl font-semibold text-foreground">
          Pre-PhD Works
        </h3>
      </div>

      <Accordion type="single" collapsible className="w-full">
        {prePhdPapers.map((paper, index) => (
          <AccordionItem key={`pre-phd-${index}`} value={`pre-phd-item-${index}`}>
            <AccordionTrigger className="text-left hover:no-underline">
              <div className="flex flex-col items-start">
                <span className="font-medium text-foreground">{paper.title}</span>
                <span className="text-sm text-text-light">{paper.status}</span>
              </div>
            </AccordionTrigger>
            <AccordionContent>
              <div className="space-y-3 pt-2">
                <p className="text-sm font-medium text-text-light">{paper.authors}</p>
                {paper.venue && <div className="text-sm text-text-light">{paper.venue}</div>}
                {paper.abstract && <p className="text-text-light leading-relaxed">{paper.abstract}</p>}
                {paper.description && !paper.abstract && <p className="text-text-light">{paper.description}</p>}
              </div>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
};

export default ResearchSection;
